server:
  port: 8069
grpc:
  port: 6996
management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]
  metrics:
    export:
      prometheus:
        enabled: true
spring:
  application:
    name: cloud-navtive-grokking-jupiter
  data:
    mongodb:
      authentication-database: admin
      database: jupiter
      port: 27017
      host: localhost
  kafka:
    listener:
      concurrency: 4
    consumer:
      bootstrap-servers: localhost:9092
      group-id: default
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 30000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 30000
      mars:
        topic: mars-message
        groupid: jupiter
