server:
  port: 8069
grpc:
  port: 6996
spring:
  data:
    mongodb:
      authentication-database: admin
      database: jupiter
      port: 27017
      host: mongo-jupiter
      username: root
      password: root
  kafka:
    listener:
      concurrency: 4
    consumer:
      bootstrap-servers: kafka-jupiter:9092
      group-id: default
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 30000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 30000
      mars:
        topic: mars-message
        groupid: jupiter
