version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  activemq:
    image: rmohr/activemq:5.14.3
    ports:
      - "61616:61616"
      - "8161:8161"
  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"