version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - jupiter_network
  kafka-jupiter:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-jupiter
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - jupiter_network
  mongo-jupiter:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - jupiter_network
  jupiter-service:
    image: jupiter-service
    environment:
      ACTIVE_PROFILE: docker
    ports:
      - "8069:8069"
      - "6996:6996"
    networks:
      - jupiter_network
    depends_on:
      - mongo-jupiter
      - kafka-jupiter
networks:
  jupiter_network:
