apiVersion: apps/v1
kind: Deployment
metadata:
    name: jupiter-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jupiter-kafka
    template:
        metadata:
            labels:
                app: jupiter-kafka
        spec:
            volumes:
                - name: config-volume
                  configMap:
                    name: jupiter-k8s-profile  
            containers:
                - name: jupiter-service
                  image: thaibao1997/jupiter:1.0.2
                  ports:
                    - name: http-port
                      containerPort: 8069
                    - name: grpc-port
                      containerPort: 6996
                  livenessProbe:
                    httpGet:
                      path: /ping
                      port: http-port
                    failureThreshold: 1
                    periodSeconds: 20
                  startupProbe:
                    httpGet:
                      path: /ping
                      port: http-port
                    failureThreshold: 30
                    periodSeconds: 10   
                  env:
                    - name: ACTIVE_PROFILE
                      value: k8s
                    - name: CONFIG_LOCATION
                      value: config/
                    - name: MONGODB_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: jupiter-mongodb
                          key: mongodb-root-password              
                  volumeMounts:
                    - name: config-volume
                      mountPath: /app/config/