// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jupiter.proto

package com.cloudnative.grokking.jupiter.api;

public final class Jupiter {
  private Jupiter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_api_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_api_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_api_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_api_PingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rjupiter.proto\022\nsample.api\"\036\n\013PingReque" +
      "st\022\017\n\007request\030\001 \001(\t\" \n\014PingResponse\022\020\n\010r" +
      "esponse\030\001 \001(\t2O\n\022JupiterGrpcService\0229\n\004p" +
      "ing\022\027.sample.api.PingRequest\032\030.sample.ap" +
      "i.PingResponseB(\n$com.cloudnative.grokki" +
      "ng.jupiter.apiP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sample_api_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sample_api_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_api_PingRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_sample_api_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sample_api_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_api_PingResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
