// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jupiter.proto

package com.cloudnative.grokking.jupiter.api;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sample.api.PingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
