// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jupiter.proto

package com.cloudnative.grokking.jupiter.api;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sample.api.PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
