apiVersion: v1
kind: Service
metadata:
    name: jupiter-kafka
spec:
    clusterIP: None
    selector:
        app: jupiter-kafka
    ports:
        - name: kafka-port
          port: 9092
          targetPort: kafka-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: jupiter-kafka
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jupiter-kafka
    template:
        metadata:
            labels:
                app: jupiter-kafka
        spec:
            containers:
                - name: zookeeper
                  image: wurstmeister/zookeeper
                  ports:
                    - name: zookeeper-port
                      containerPort: 2181
                - name: kafka
                  image: wurstmeister/kafka
                  ports:
                    - name: kafka-port
                      containerPort: 9092
                  env:
                    - name: KAFKA_ADVERTISED_HOST_NAME
                      value: jupiter-kafka
                    - name: KAFKA_ZOOKEEPER_CONNECT
                      value: localhost:2181
                    