apiVersion: v1
kind: Service
metadata:
    name: jupiter-mongodb
spec:
    type: ClusterIP
    selector:
        app: jupiter-mongodb
    ports:
        - name: mongodb-port
          targetPort: mongodb-port
          port: 27017
          protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
    name: jupiter-mongodb
type: Opaque
data:
    mongodb-root-password: cm9vdA==
    #root
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: jupiter-mongodb-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jupiter-mongodb
    template:
        metadata:
            labels:
                app: jupiter-mongodb
        spec:
            containers:
                - name: mongodb
                  image: mongo
                  ports:
                    - name: mongodb-port
                      containerPort: 27017
                  env:
                    - name: MONGO_INITDB_ROOT_USERNAME
                      value: root
                    - name: MONGO_INITDB_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: jupiter-mongodb
                            key: mongodb-root-password   
